name: Pipeline-IC-Actions

# 1. Cuándo se ejecuta (Trigger)
on: [push]

# 2. Qué hace (Jobs)
jobs:
  build-and-test:
    # 3. El equivalente a 'agent any' (usa una máquina Linux en la nube)
    runs-on: ubuntu-latest

    steps:
      # Paso 1: "Clonar" tu repositorio en la máquina virtual
      - name: Descargar código
        uses: actions/checkout@v4

      # Paso 2: Instalar Python en la máquina virtual
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Podés poner la versión que uses

      # Paso 3: Ejecutar los tests (igual que en Jenkins, pero con 'run' en vez de 'bat')
      - name: Ejecutar pruebas unitarias
        run: python -m unittest test_app.py

      # Paso 4: Notificación de Éxito a Discord
      - name: Notificar éxito a Discord
        if: success() # Solo se ejecuta si el paso anterior (los tests) salió bien
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "${{github.actor}}¡Exito! El pipeline paso correctamente en GitHub Actions."}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      # Paso 5: Notificación de Error a Discord
      - name: Notificar error a Discord
        if: failure() # Solo se ejecuta si los tests fallaron
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "${{github.actor}}¡Error! El pipeline fallo en GitHub Actions. Alguien rompio el codigo."}' \
          ${{ secrets.DISCORD_WEBHOOK }}