name: Pipeline-IC-Actions

on: [push]

jobs:
  # ==========================================
  # JOB 1: CONSTRUCCIÓN Y PRUEBAS
  # ==========================================
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # SonarCloud necesita el historial completo para funcionar bien

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas unitarias
        run: python -m unittest test_app.py

      - name: Ejecutar pruebas de comportamiento (BDD)
        run: behave

      - name: Análisis de Código estático (SonarCloud)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # ==========================================
  # JOB 2: DESPLIEGUE EN RENDER
  # ==========================================
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en Render
        # Al poner 'needs: build-and-test', este job solo arranca si el anterior fue exitoso.
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  # ==========================================
  # JOB 3: ACTUALIZAR TRELLO
  # ==========================================
  trello:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código (para leer el commit)
        uses: actions/checkout@v4

      - name: Extraer ID y Actualizar Trello
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          CARD_ID=$(echo "$COMMIT_MSG" | grep -oPi 'trello/trello-\K[a-z0-9]+' || true)
          echo "Se encontro el ID de Trello: $CARD_ID"
          
          if [ ! -z "$CARD_ID" ]; then
            curl -X PUT "https://api.trello.com/1/cards/${CARD_ID}?idList=${{ secrets.TRELLO_LIST_ID }}&key=${{ secrets.TRELLO_API_KEY }}&token=${{ secrets.TRELLO_TOKEN }}"
          else
            echo "No se encontro ID de Trello en el commit. Ignorando."
          fi

  # ==========================================
  # JOB 4: NOTIFICACIÓN EN DISCORD
  # ==========================================
  notificacion:
    needs: build-and-test
    runs-on: ubuntu-latest
    # IMPORTANTE: if: always() asegura que este job corra INCLUSO si los tests fallaron
    if: always() 
    steps:
      - name: Notificar éxito a Discord
        if: needs.build-and-test.result == 'success'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "${{github.actor}} ¡Exito! El pipeline paso correctamente en GitHub Actions."}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notificar error a Discord
        if: needs.build-and-test.result == 'failure'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "${{github.actor}} ¡Error! El pipeline fallo en GitHub Actions. No pasaron los test!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}